<?php
// $Id: project_issue_generate.module,v 1.3 2007-12-16 02:45:57 dww Exp $

/**
 * Implementation of hook_menu().
 */
function project_issue_generate_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array(
      'path' => 'admin/project/generate_issue',
      'title' => t('Generate issues'),
      'description' => t('Generate a given number of issues.'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('project_issue_generate_issues_form'),
      'access' => user_access('administer nodes'),
    );
  }

  return $items;
}

function project_issue_generate_issues_form() {
  $form['issues'] = array(
    '#type' => 'textfield',
    '#title' => t('How many issues would you like to generate?'),
    '#default_value' => 100,
    '#size' => 10,
  );
  $form['comments'] = array(
    '#type' => 'textfield',
    '#title' => t('How many issue comments would you like to generate?'),
    '#default_value' => 200,
    '#size' => 10,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Do it!'),
  );
  return $form;
}

function project_issue_generate_issues_form_submit($form_id, $form_values) {
  $file = drupal_get_path('module', 'project_issue_generate') .'/project_issue_generate.inc';
  require_once($file);
  project_issue_generate_issues($form_values['issues']);
  project_issue_generate_issue_comments($form_values['comments']);
}
