<?php
// $Id: project_issue_generate.module,v 1.5 2009-01-20 18:38:03 dww Exp $

/**
 * Implementation of hook_menu().
 */
function project_issue_generate_menu() {
  $items = array();
  $items['admin/project/generate_issue'] = array(
    'title' => 'Generate issues',
    'description' => 'Generate random issues and issue comments.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('project_issue_generate_issues_form'),
    'access arguments' => array('administer nodes'),
  );
  return $items;
}

function project_issue_generate_issues_form($form_state) {
  $form['issues'] = array(
    '#type' => 'textfield',
    '#title' => t('How many issues would you like to generate?'),
    '#default_value' => 100,
    '#size' => 4,
  );
  $form['comments'] = array(
    '#type' => 'textfield',
    '#title' => t('How many issue comments would you like to generate?'),
    '#default_value' => 200,
    '#size' => 4,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Do it!'),
  );
  return $form;
}

function project_issue_generate_issues_form_submit($form, &$form_state) {
  $path = drupal_get_path('module', 'project_issue_generate');
  module_load_include('inc', 'project_issue_generate', 'project_issue_generate');
  project_issue_generate_issues($form_state['values']['issues']);
  project_issue_generate_issue_comments($form_state['values']['comments']);
}

